<!doctype html>
<html lang="es">
<head>
	<meta charset="UTF-8" />
	<title>Tienda</title>
	<link rel=Stylesheet href="css/movil.css" media='screen and (min-width: 1px) and (max-width: 800px)'>
	<link rel=Stylesheet href="css/pcmac.css" media='screen and (min-width: 801px) and (max-width: 4000px)'>
</head>
<body>
	<div id="contenedor">
		<header>
			<h1>Tienda</h1>
			<h2>Subtitulo de la tienda </h2>
		</header>
		<section>